language: python
python: 3.4
addons:
  postgresql: 9.3
services:
  - postgresql
install:
  - pip install Click psycopg2
env:
  - LC_ALL=C.UTF-8 POSTGRES_USER=postgres POSTGRES_PASSWORD=''
script:
  - nosetests -v test/
